// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUa0gDS1AFvP-zJjz3ZVg19VRQUe5rtDc',
    appId: '1:226983170954:web:9b926c024c916bad832e73',
    messagingSenderId: '226983170954',
    projectId: 'semi-final-lab-a20ae',
    authDomain: 'semi-final-lab-a20ae.firebaseapp.com',
    storageBucket: 'semi-final-lab-a20ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtuHbIvMkuHTHt7rCaLJ3mFX4tCPuqeb4',
    appId: '1:226983170954:android:4603ca74fe5c1be7832e73',
    messagingSenderId: '226983170954',
    projectId: 'semi-final-lab-a20ae',
    storageBucket: 'semi-final-lab-a20ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhWoNa8bbWKW_LJfxlUHyJoY5J_Kp8hQ',
    appId: '1:226983170954:ios:11bf6c3996b06dd2832e73',
    messagingSenderId: '226983170954',
    projectId: 'semi-final-lab-a20ae',
    storageBucket: 'semi-final-lab-a20ae.appspot.com',
    iosClientId: '226983170954-m4c22j5rgj2smm8v88hp014h49c0mg5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.semiFinalLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMhWoNa8bbWKW_LJfxlUHyJoY5J_Kp8hQ',
    appId: '1:226983170954:ios:11bf6c3996b06dd2832e73',
    messagingSenderId: '226983170954',
    projectId: 'semi-final-lab-a20ae',
    storageBucket: 'semi-final-lab-a20ae.appspot.com',
    iosClientId: '226983170954-m4c22j5rgj2smm8v88hp014h49c0mg5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.semiFinalLab',
  );
}
